---
apiVersion: v1
kind: Service
metadata:
  name: txwatchdb
  namespace: nft-dev
  labels:
    app: txwatchdb
spec:
  type: ClusterIP
  selector:
    app: txwatchdb
  ports:
    - protocol: TCP
      port: 5432
      name: postgres
      targetPort: 5432
